name: Multi-Build-snapshot-opwrt
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Multi-Build-snapshot-opwrt.yml'
  schedule:
        - cron: 0 14 * * *
  workflow_dispatch:

env:
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: true

jobs:

  Raspberry3:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone source and install
      run: |
        git clone https://github.com/openwrt/openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Download and Load custom configuration ssnordsqconfig
      run: |
        cd openwrt
        curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/rpi/ssnordsqconfig >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/diy.sh | grep -v 'zzz-default-settings' )
        make defconfig
        
    - name: Download package ssnordsqconfig
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        which opl2ofm || { pushd package/custom/openwrt-packages/luci-app-openclash/tools/po2lmo ; make install ; popd ; } 
        
    - name: Multi-core compile ssnordsqconfig
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc)
        sudo df -h
        
    - name: Single-core compile ssnordsqconfig
      if: failure()
      run: |
        sudo df -h
        cd openwrt
        make -j1 V=s
        sudo df -h

    - name: make zip RaspberryPi3b_ssnordsq.zip and uplod
      if: success()
      run: |
        cd openwrt/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_ssnordsq_$(date -I).zip . -i *
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3b_ssnordsq_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com RaspberryPi3b_ssnordsq_$(date -I).zip ::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_ssnordsq_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com RaspberryPi3b_ssnordsq_$(date -I).zip ::$(cat cowtransfer.log | grep https)"
        rm *.img.gz
        rm RaspberryPi3b_ssnordsq_$(date -I).zip

    - name: Load custom configuration ssnordsqconfigmp
      run: |
        cd openwrt
        curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/rpi/ssnordsqconfigmp >.config
        make defconfig
        
    - name: Multi-core compile ssnordsqconfigmp
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc)
        sudo df -h
        
    - name: Single-core compile ssnordsqconfigmp
      if: failure()
      run: |
        sudo df -h
        cd openwrt
        make -j1 V=s
        sudo df -h

    - name: make zip RaspberryPi3b_ssnordsqmp.zip and uplod
      if: success()
      run: |
        cd openwrt/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_ssnordsqmp_$(date -I).zip . -i *
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3b_ssnordsqmp_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com RaspberryPi3b_ssnordsqmp_$(date -I).zip ::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_ssnordsqmp_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com RaspberryPi3b_ssnordsqmp_$(date -I).zip ::$(cat cowtransfer.log | grep https)"
        rm *.img.gz
        rm RaspberryPi3b_ssnordsqmp_$(date -I).zip