name: Build-Lean-lede
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Multi-Build-Lean-lede.yml'
  schedule:
        - cron: 0 14 * * *
  workflow_dispatch:

env:
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true

jobs:

  Raspberry3:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone source and install
      run: |
        git clone https://github.com/coolsnowwolf/lede
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Download and Load custom configuration nordext4config
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/rpi/nordext4config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package nordext4config
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        which opl2ofm || { pushd package/custom/openwrt-packages/luci-app-openclash/tools/po2lmo ; make install ; popd ; } 
        
    - name: Multi-core compile nordext4config
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc)
        sudo df -h
        
    - name: Single-core compile nordext4config
      if: failure()
      run: |
        sudo df -h
        cd lede
        make -j1 V=s
        sudo df -h

    - name: make zip RaspberryPi3b_nordext4.zip and uplod
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_nordext4_$(date -I).zip . -i *
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3b_nordext4_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_nordext4_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        rm RaspberryPi3b_nordext4_$(date -I).zip

    - name: Load custom configuration gzrdext4config
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/rpi/gzrdext4config >.config
        make defconfig
        
    - name: Multi-core compile gzrdext4config
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc)
        sudo df -h
        
    - name: Single-core compile gzrdext4config
      if: failure()
      run: |
        sudo df -h
        cd lede
        make -j1 V=s
        sudo df -h

    - name: make zip RaspberryPi3b_gzrdext4.zip and uplod
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_gzrdext4_$(date -I).zip . -i *
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3b_gzrdext4_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_gzrdext4_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        rm RaspberryPi3b_gzrdext4_$(date -I).zip

    - name: Load custom configuration nordsqconfig
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/rpi/nordsqconfig >.config
        make defconfig
       
    - name: Multi-core compile nordsqconfig
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc)
        sudo df -h
        
    - name: Single-core compile nordsqconfig
      if: failure()
      run: |
        sudo df -h
        cd lede
        make -j1 V=s
        sudo df -h

    - name: make zip RaspberryPi3b_nordsq.zip and uplod
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_nordsq_$(date -I).zip . -i *
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3b_nordsq_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_nordsq_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        rm RaspberryPi3b_nordsq_$(date -I).zip

    - name: Load custom configuration gzrdsqconfig
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/rpi/gzrdsqconfig >.config
        make defconfig
       
    - name: Multi-core compile gzrdsqconfig
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc)
        sudo df -h
        
    - name: Single-core compile gzrdsqconfig
      if: failure()
      run: |
        sudo df -h
        cd lede
        make -j1 V=s
        sudo df -h

    - name: make zip RaspberryPi3b_gzrdsq.zip and uplod
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_gzrdsq_$(date -I).zip . -i *
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3b_gzrdsq_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_gzrdsq_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        rm RaspberryPi3b_gzrdsq_$(date -I).zip