name: Multi-Build-snapshot-opwrt
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Multi-Build-snapshot-opwrt.yml'
  schedule:
        - cron: 0 14 * * *
  workflow_dispatch:

env:
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: true

jobs:

  Raspberry3:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/prenv.sh)


    - name: Clone source and install
      run: |
        git clone https://github.com/openwrt/openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Download and Load custom configuration
      run: |
        cd openwrt
        ./scripts/feeds uninstall luci-app-smartdns smartdns libiio
        curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/rpi/ssconfig >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/gzmud/My-action/master/lean-lede/diy.sh | grep -v 'zzz-default-settings' )
        rm -rf package/custom/luci-app-dockerman-0.5.13
        rm -rf package/custom/luci-app-smartdns
        rm -rf package/custom/openwrt-smartdns 
        rm -rf package/custom/luci-theme-argon package/custom/luci-theme-atmaterial
        rm -rf package/custom/openwrt-package/lienol/luci-theme-* package/custom/openwrt-packages/luci-theme-*
        pushd package/custom
        git clone https://github.com/lisaac/luci-app-diskman
        mkdir parted
        mv luci-app-diskman/Parted.Makefile parted/Makefile
        popd
        make defconfig
        
    - name: Download package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        which opl2ofm || { pushd package/custom/openwrt-packages/luci-app-openclash/tools/po2lmo ; make install ; popd ; } 
        cd staging_dir/host/bin
        ln -s `command -v upx`
        
    - name: Multi-core compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc)
        sudo df -h
        
    - name: Single-core compile
      if: failure()
      run: |
        sudo df -h
        cd openwrt
        make -j1 V=s
        sudo df -h

    - name: Single-core compile failure
      if: failure()
      run: |
        sudo df -h
        cd openwrt
        tar czf buildroot_$(date -I).tar.gz -C .
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress buildroot_$(date -I).tar.gz 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com buildroot_$(date -I).tar.gz ::$(cat wetransfer.log | grep https)"

    - name: make zip RaspberryPi3b_ssnordext4.zip and upload
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_ssnordext4_$(date -I).zip . -i * -x "*-squashfs-*.img.gz" -x "*-rootfs.tar.gz" -x "*-imagebuilder-*.tar.xz" -x "*-sdk-*.tar.xz" -x "*-toolchain-*.tar.*"
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3b_ssnordext4_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com RaspberryPi3b_ssnordext4_$(date -I).zip ::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_ssnordext4_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com RaspberryPi3b_ssnordext4_$(date -I).zip ::$(cat cowtransfer.log | grep https)"
        rm *-ext4-*.img.gz
        rm RaspberryPi3b_ssnordext4_$(date -I).zip

    - name: make zip RaspberryPi3b_ssnordsq.zip and upload
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_ssnordsq_$(date -I).zip . -i * -x "*-ext4-*.img.gz" -x "*-rootfs.tar.gz" -x "*-imagebuilder-*.tar.xz" -x "*-sdk-*.tar.xz" -x "*-toolchain-*.tar.*"
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3b_ssnordsq_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com RaspberryPi3b_ssnordsq_$(date -I).zip ::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_ssnordsq_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com RaspberryPi3b_ssnordsq_$(date -I).zip ::$(cat cowtransfer.log | grep https)"
        rm *-squashfs-*.img.gz
        rm RaspberryPi3b_ssnordsq_$(date -I).zip

    - name: make zip RaspberryPi3b_ssimgsdk.zip and upload
      if: success()
      run: |
        cd lede/bin/targets/*/*
        zip -r -o -q RaspberryPi3b_ssimgsdk_$(date -I).zip . -i * -x "*-rootfs.tar.gz" -x "*-toolchain-*.tar.*"
        curl -fsSL git.io/file-transfer | sh
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && ./transfer wet -s -p 16 --no-progress RaspberryPi3bRaspberryPi3b_ssimgsdk__imgsdk_$(date -I).zip 2>&1 | tee wetransfer.log
        test ${{ env.UPLOAD_WETRANSFER }} == 'true' && echo "::warning file=wetransfer.com RaspberryPi3b_ssimgsdk_$(date -I).zip ::$(cat wetransfer.log | grep https)"
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && ./transfer cow --block 2621440 -s -p 64 --no-progress RaspberryPi3b_ssimgsdk_$(date -I).zip 2>&1 | tee cowtransfer.log
        test ${{ env.UPLOAD_COWTRANSFER }} == 'true' && echo "::warning file=cowtransfer.com RaspberryPi3b_ssimgsdk_$(date -I).zip ::$(cat cowtransfer.log | grep https)"
        rm RaspberryPi3b_ssimgsdk_$(date -I).zip